// <auto-generated />
using LexoRank.Test.Bucket.Nested.Database;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace LexoRank.Test.Bucket.Nested.Migrations
{
    [DbContext(typeof(MyDbContext))]
    partial class MyDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("LexoRank.Test.Bucket.Database.Entities.Post", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("SortingValue")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Posts");
                });

            modelBuilder.Entity("LexoRank.Test.Bucket.Nested.Database.Entities.LexoRankData", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.PrimitiveCollection<string[]>("Buckets")
                        .IsRequired()
                        .HasColumnType("text[]");

                    b.Property<string>("CharacterSet")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("CurrentBucket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("DenominatorBase")
                        .HasColumnType("integer");

                    b.Property<int>("DenominatorExponent")
                        .HasColumnType("integer");

                    b.Property<bool>("IsDesc")
                        .HasColumnType("boolean");

                    b.Property<bool>("IsRebalancing")
                        .HasColumnType("boolean");

                    b.Property<string>("LastLexoRankValueNumerator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NextBucket")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<char>("Separator")
                        .HasColumnType("character(1)");

                    b.Property<string>("StepSizeNumerator")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LexoRankData");
                });
#pragma warning restore 612, 618
        }
    }
}
